apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  grafana.ini: |
    [server]
    domain = 34.159.86.5
    root_url = http://34.159.86.5/grafana
    serve_from_sub_path = true
    [security]
    allow_embedding = true
    cookie_secure = false
    cookie_samesite = lax
    [auth]
    disable_login_form = false
    disable_signout_menu = false
    login_cookie_name = grafana_session
    [paths]
    proxy_subpath = /grafana