apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-k8s
rules:
  - apiGroups: [""]
    resources:
      ["nodes/metrics", "nodes/proxy", "nodes"]
    verbs: ["get", "list", "watch"]