apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: kube-prometheus-stack
    app.kubernetes.io/instance: kube-prometheus-stack
    release: kube-prometheus-stack
  name: custom-rules
spec:
  groups:
  - name: custom.rules
    rules:
    - alert: HighCPUUsage
      expr: rate(container_cpu_usage_seconds_total{pod=~"web-app.*"}[5m]) > 0.8
      for: 5m
      labels:
        severity: warning
      annotations:
        description: "High CPU usage detected"
    - alert: HighMemoryUsage
      expr: container_memory_usage_bytes{pod=~"web-app.*"} > 450Mi
      for: 5m
      labels:
        severity: warning
      annotations:
        description: "High memory usage detected"