apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: web-app-servicemonitor
  namespace: monitoring
  labels:
    app: web-app
    release: prometheus
spec:
  selector:
    matchLabels:
      app: web-app
  namespaceSelector:
    matchNames:
      - default
  endpoints:
  - port: "metrics"
    interval: 15s
    path: /metrics