global:
  rbac:
    createAggregateClusterRoles: false

kubeProxy:
  enabled: false

kubelet:
  enabled: false

kubeScheduler:
  enabled: false

kubeControllerManager:
  enabled: false

kubeEtcd:
  enabled: false

prometheusOperator:
  tls:
    enabled: false
  admissionWebhooks:
    enabled: false
    patch:
      enabled: false
  namespaces:
    releaseNamespace: true
    additional:
      - monitoring
      - default
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

prometheus:
  prometheusSpec:
    podMonitorNamespaceSelector: {}
    serviceMonitorNamespaceSelector: {
      matchNames: ["default", "monitoring"]
    }
    podMonitorSelector: {}
    serviceMonitorSelector: {
      matchLabels: {
        app: web-app,
        release: prometheus
      }
    }
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    retention: 5d
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

alertmanager:
  enabled: true
  alertmanagerSpec:
    storage: {}
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

grafana:
  adminPassword: "bkuDCAYjlZsOgdi71Q80"
  grafana.ini:
    server:
      serve_from_sub_path: true
      root_url: "http://34.159.86.5/grafana/"
      domain: "34.159.86.5/grafana/"
    auth:
      login_cookie_name: grafana_session
      signout_redirect_url: /grafana/
      login_maximum_inactive_lifetime_duration: 7d
      login_maximum_lifetime_duration: 30d
  persistence:
    enabled: true
    type: pvc
    size: 10Gi
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

coreDns:
  enabled: false

nodeExporter:
  enabled: false

defaultRules:
  create: true
  rules:
    kubeScheduler: false
    kubeProxy: false
    etcd: false
    kubeControllerManager: false