global:
  rbac:
    createAggregateClusterRoles: false

kubeProxy:
  enabled: false

kubelet:
  enabled: false

kubeScheduler:
  enabled: false

kubeControllerManager:
  enabled: false

kubeEtcd:
  enabled: false

prometheusOperator:
  tls:
    enabled: false
  admissionWebhooks:
    enabled: false
    patch:
      enabled: false
  namespaces:
    releaseNamespace: true
    additional:
      - monitoring
      - default
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

prometheus:
  prometheusSpec:
    externalUrl: "http://34.159.86.5/prometheus/"
    routePrefix: /prometheus
    addtionalScrapeConfigs:
      - job_name: 'kubernetes-pods-cadvisor'
        scheme: https
        metrics_path: /metrics/cadvisor
        kubernetes_sd_configs:
          - role: node
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        tls_config:
          insecure_skip_verify: true
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
      # - job_name: kubernetes-nodes
      #   kubernetes_sd_configs:
      #     - role: node
      #   tls_config:
      #     ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      #   bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      #   scheme: https
      #   metrics_path: /metrics/cadvisor
    podMonitorNamespaceSelector: {}
    serviceMonitorNamespaceSelector: {}
    podMonitorSelector: {}
    serviceMonitorSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    retention: 5d
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

alertmanager:
  enabled: true
  alertmanagerSpec:
    externalUrl: "https://http://34.159.86.5/alertmanager/"
    routePrefix: /alertmanager
    storage: {}
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

grafana:
  env:
    GF_SERVER_SERVE_FROM_SUB_PATH: true
    GF_SERVER_ROOT_URL: "http://34.159.86.5/grafana/"
  grafana.ini:
    server:
      domain: "34.159.86.5"
      root_url: "http://34.159.86.5/grafana/"
  adminPassword: "bkuDCAYjlZsOgdi71Q80"
  persistence:
    enabled: true
    type: pvc
    size: 10Gi
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

coreDns:
  enabled: false

nodeExporter:
  enabled: false

defaultRules:
  create: true
  rules:
    kubeScheduler: false
    kubeProxy: false
    etcd: false
    kubeControllerManager: false