apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - web-app.yaml
  - monitoring/web-app-dashboard.yaml
  - monitoring/web-app-prometheusrule.yaml
  - monitoring/web-app-servicemonitor.yaml
  - monitoring/grafana-config.yaml
  - monitoring/monitoring-ingress.yaml
  #- service.yaml