apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - load-generator.yaml
  - monitoring/custom-alert-rules.yaml
  - monitoring/kubelet-scraping.yaml
  - monitoring/monitoring-ingress.yaml
  - monitoring/prometheus-clusterrole.yaml
  - monitoring/prometheus-clusterrolebinding.yaml
  - monitoring/prometheus-forwarder.yaml
  - monitoring/prometheus-prometheus.yaml
  - monitoring/web-app-dashboard.yaml
  - monitoring/web-app-servicemonitor.yaml
  - web-app/default-ingress.yaml
  - web-app/statsd-mapping-config.yaml
  - web-app/web-app-hpa.yaml
  - web-app/web-app.yaml