apiVersion: v1
kind: ConfigMap
metadata:
  name: statsd-mapping-config
  namespace: default
data:
  mapping.conf: |
    mappings:
    - match: "http_requests_total"
      name: "http_requests_total"
      labels:
        app: "web-app"