apiVersion: v1
kind: ConfigMap
metadata:
  name: web-app-configmap
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'web-app'
        static_configs:
          - targets: ['localhost:8080']